[package]
name = "day01"
version = "0.1.0"
authors = ["Elliot Davies <elliot.a.davies@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
